version: "3"

services:
  postgres:
    image: postgres:15.0-alpine
    container_name: postgresFood
    environment:
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=postgresFood
    volumes:
      - postgresFood:/var/lib/postgresql/data
    ports:
      - 5430:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadminFood
    image: dpage/pgadmin4
    ports:
      - "8081:80"
    volumes:
      - postgresFood:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - postgres

volumes:
  postgresFood:

networks:
  postgres:
    driver: bridge
